#include <iostream>
#include <fstream>
#include <string>

#include "../inc/constellation.h"
#include "henry_draper.h"
#include "hipparcos.h"

using namespace std;

#pragma pack(1)

int main()
{
	ofstream generated_file("../inc/constellation_data.generated.h");

	generated_file << "// this file was generated by the origami-sunset star catalog analyis tool." << endl;

	auto hd_data = readTDat_HD("../catalog/heasarc_hd.tdat");
	auto hip_data = readTDat_HIP("../catalog/heasarc_hipparcos.tdat");

	generated_file.close();

	return 0;
}
