#include <iostream>
#include <fstream>
#include <string>

#include "../inc/constellation.h"
#include "henry_draper.h"
#include "hipparcos.h"
#include "messier.h"
#include "ngc2000.h"
#include "constel.h"

using namespace std;

#pragma pack(1)

int main()
{
	ofstream generated_file("../inc/constellation_data.generated.h");

	generated_file << "// this file was generated by the origami-sunset star catalog analyis tool." << endl;

	auto hd_data = loadHD("../catalog");
	auto hip_data = loadHIP("../catalog");
	auto mes_data = loadMes("../catalog");
	auto ngc_data = loadNGC("../catalog");

	// TODO: bayer
	// TODO: flamsteed
	// TODO: merge

	auto constellations = loadConstellations("../catalog");

	generated_file.close();

	return 0;
}
